### PR TITLE
Added support for PNG images

### PR DESCRIPTION
**Pull request by CWBudde**
Beside some minor formatting (to get into the source code easier), I added support for PNG images (e.g. to support the mORMot icon)

### CODE REVIEW

**Comment by Memnarch** [comment]
Thanks,
Already thought about adding PNG and wanted to add it this evening. 2 "problems" occur here:
1) You must use undecorated unitnames, otherwhise it'll not compile on Delphi XE
2) This project runs under a "everything is mine" licence atm as i haven't specified one, yet. By contributing you loose Copyright of your changes :(

**Comment by CWBudde** [comment]
Hello Alexander,

> 1) You must use undecorated unitnames, otherwhise it'll not compile on
> Delphi XE
>

No problem. I don't have XE, so I couldn't test this, but I thought EMB
already renamed it when they introduced namespaces.

> 2) This project runs under a "everything is mine" licence atm as i
> haven't specified one, yet. By contributing you loose Copyright of
> your changes :(
>

No problem. I just wanted to see whether the icon I had for the
AggPasMod project worked or not. When I saw that it had to be jpg there
were two options: Convert the image or add support to Delphinus. Since
the mORMot package profit from the changes as well I have chosen the
second option. Even if I loose the copyright, it is at least now working
and I do not need to convert the image.

Kind regards,

    Christian


-- 
Christian-W. Budde
Eleonorenstr. 17
30449 Hannover
Tel.: +49 511 31048857
E-Mail: Christian@savioursofsoul.de
WWW: http://www.savioursofsoul.de/Christian

**Comment by Memnarch** [comment]
Sounds good, can you do the changes regarding undecorated unitnames? i can't change the files right now.

**Comment by CWBudde** [comment]
Done

**Comment by Memnarch** [comment]
already merged :)

**Pull request merged**
