### PR TITLE
Fixes in package details

### PR DESCRIPTION
**Pull request by Pawe1**
No more 'null' in description.
Also fixed bug with invisible TLabel text when package description was long.
Added ellipsis for case when license name is too long to display.

I hope VCL in older Delphi versions supports TLabel.EllipsisPosition property...

### CODE REVIEW

**Comment by Memnarch** [comment]
Ellipsis is available in XE(that is the MinVersion to support) but stringhelpers are from XE8 and newer ;)
A simple if trim(X) = '' then is enough here. (Strings can't be null anyway)

**Comment by Pawe1** [comment]
By "null" i meant that when description is empty this line
`LPackage.Description := AItem.GetValue('description').Value;`
evaluates to '**null**' and it just looks strange...

String helpers => oh... I have used this at XE7, but this can be replaced with
`if Length(Trim(FPackage.Description)) then`

**Comment by Memnarch** [comment]
With "Null" i meant IsNullOrWhiteSpace. Everytime i read this Bullshit, i want to hit a RTL-Developer very hard for C6P without using their brain -.-

**Comment by Pawe1** [comment]
Yup... Naming of s some RTL elements is really far from being cohesive.
There are really modern pieces... and some that look like nobody touched them since D4 / D7...
Entropy FTW :stuck_out_tongue:

**Comment by Pawe1** [comment]
I don't insist that `lbDescription` should display package name, but for me displaying big **null** is a bug, not a feature 😉

**Comment by Memnarch** [comment]
But i insist on removing the stringhelper :P

**Comment by Pawe1** [comment]
I removed TStringHelper references but left description conditional.
IMHO empty space there in some packages would look strange...

**Comment by Memnarch** [comment]
looks better, i'Ll rebase it tomorrow

**Comment by Pawe1** [comment]
You don't like merges, don't You? xD
Sorry - I'm not in the "rebase team" :P Also in every company I have worked yet official workflow avoided rebasing xD

**Comment by Memnarch** [comment]
as long as it is a single commit, i simply rebase. Otherwhise single commits end up as 2(commit + mergecommit) in Histories. Since Githubs timeline is pretty basic you don't see it. But in any proper Desktop-Tool it can become a nightmare to read :P

**Comment by Pawe1** [comment]
xD xD xD

Git-hero

**Comment by Memnarch** [comment]
Horrible isn't it? :D

**Pull request merged**
