### PR TITLE
Support for new platforms

### PR DESCRIPTION
**Pull request by Pawe1**
A little update for this branch.
I did a quick smoke test with Android and it seems that this code works :wink: 

Displayed OS icons are now a bit reordered.

### CODE REVIEW

**Comment by Pawe1** [comment]
Oook... I've found a problem with Android platform...

Android compiler really don't like when path contains spaces... So much that it don't work 😢 
**So it raises a new question: Should Delphinus sanitize package names in TDNSetupCore.GetInstallDirectoryForPackage method?...**

**Comment by Memnarch** [comment]
AH FINALLY a testsubject for Mobile platforms :D. As i am curious, can you give some more details on the errors?

**Comment by Pawe1** [comment]
> "Oh, look! Here is an explorer!" he exclaimed to himself when he saw the little prince coming.
:wink: 

I'll write more after weekend :)

**Comment by Pawe1** [comment]
Funny fact.... problem with spaces disappeared after restarting PC... Don't ansk... :dizzy_face: 
Sometimes Delphi keeps me amazed (because of how random IDE works)...

Also there is a tiny problem with painting space :stuck_out_tongue_closed_eyes: 
Alternative

BTW in registry there are patches
```
HKEY_CURRENT_USER\Software\Embarcadero\BDS\19.0\Library\Android32
HKEY_CURRENT_USER\Software\Embarcadero\BDS\19.0\Library\iOSDevice32
HKEY_CURRENT_USER\Software\Embarcadero\BDS\19.0\Library\iOSDevice64
HKEY_CURRENT_USER\Software\Embarcadero\BDS\19.0\Library\iOSSimulator
HKEY_CURRENT_USER\Software\Embarcadero\BDS\19.0\Library\Linux64
HKEY_CURRENT_USER\Software\Embarcadero\BDS\19.0\Library\OSX32
HKEY_CURRENT_USER\Software\Embarcadero\BDS\19.0\Library\Win32
HKEY_CURRENT_USER\Software\Embarcadero\BDS\19.0\Library\Win64
```
I don't knof if it means that iOS simulator is 32/64-bit agnostic... :roll_eyes:

**Comment by Memnarch** [comment]
I have never been sure about the IOSSimulator. SHould i add it? Should i automatically add it when IOS32 is supported?(simulator has no 64bit as far as i know)

**Comment by Pawe1** [comment]
........
Problem with spaces still exist - I opened wrong project :blush: 

What happens?
[DCC Fatal Error] Main.pas(57): F2613 Unit 'blah.blah' not found.

**Comment by Memnarch** [comment]
what happens if the path ends with a '\'?
And does this really affect the android compiler, only?

**Comment by Pawe1** [comment]
Ok - looks like solved.
This was my fault - I had no idea that IDE has to be restarted after touching library / browsing patches

**Comment by Pawe1** [comment]
There is another stupid naming question:
So if there is "Android32" should we call Android "Android" or "Android32"?...

**Comment by Memnarch** [comment]
I go with the platformnames of the projectfiles. If it is called Android, i call it Android, if it is called Android32 i call it Android32

**Comment by Pawe1** [comment]
Somethimes the rules change during game :smile: 
Like "Mac OS X" that became "OS X" and now is "macOS" so project names not always comply with a reality :dizzy_face:

**Comment by Memnarch** [comment]
don't add simulator for now

**Comment by Pawe1** [comment]
OK
So it looks like that's all for this moment.

If You decide to merge it into master I'll try to ask some more people to publish their packages.

**Comment by Memnarch** [comment]
please rebase your version, since Mobile-Branch was missing some comitts

**Comment by Pawe1** [comment]
Your rebase was unnecessary because I merged back "master" branch into feature branch so nothing was missing :wink: 
Rebasing pushed branches doesn't seem to be the best idea but ok - I have cherrypicked all of these commits.

**Comment by Memnarch** [comment]
Thanks, i'll merge this back this evening

**Comment by Memnarch** [comment]
one little sidenode: ANdroid is not meaned to be Android32 but Android. 32/64 has been used by emba fpr X86 and X64 Platforms and android is ARM, so i am not sure rn oO

**Comment by Pawe1** [comment]
In Windows Registry Android key is named Android32.
It was the cause I asked a question about how to name Android parameter.

**Comment by Memnarch** [comment]
1) Then i should name it Android32 everywhere
2) Well if android works, i'd say see what happens in the wild :P
3) For now i'll simply ingore the emulator and see what happens
4) I'll fix the icon issue later. First we need more packages which really make use of them

**Comment by Pawe1** [comment]
1 => In `.dpk` it is called `Android` ([see example](https://github.com/Pawe1/Sprinkles/blob/master/Packages/Delphi%2010.2/Sprinkles.Base.dproj)) but in Windows Registry `Android32`... Hell yea...

4 => Nice candidates: [Spelt/ZXing.Delphi](https://github.com/Spelt/ZXing.Delphi) / [grijjy/GrijjyFoundation](https://github.com/grijjy/GrijjyFoundation)
[I have already posted one pull request](https://github.com/Spelt/ZXing.Delphi/pull/52)

BTW - **shouldn't Delphinus warn user that changes in browsing/search patches require IDE restart?**

**Comment by Memnarch** [comment]
Well usually changing searchpathes should apply directly. But it seems my hack missing a call somewhere :P

**Comment by Memnarch** [comment]
okay mobile is now in master

**Comment by Pawe1** [comment]
Wow :grin: 
Thx!

**Comment by Memnarch** [comment]
btw i created a dummy pullrequest on your spring4d copy as you should remove your Spring4D copy. I expect sglienke to update his version soon :)

**Comment by Pawe1** [comment]
Ok, great :smile:

**Comment by Pawe1** [comment]
@Memnarch I'm wondering...
Why do `IOSDevice32` + `IOSDevice64` consts (used in JSON properties) start with capital letter?...

**Comment by Memnarch** [comment]
Because i don't care much about Apple and stay within PascalNotation :P

**Pull request merged**
